### ISSUE TITLE
Getting error while create spoke

### ISSUE THREAD

**Issue by rocki9satya** [aws-samples/aws-network-hub-for-terraform#20] opened 2022-06-05 03:34 UTC
Error: error updating EC2 Transit Gateway Attachment (tgw-attach-0d42be5b321cc1c72) Route Table () association: error associating EC2 Transit Gateway Route Table () association (tgw-attach-0d42be5b321cc1c72): MissingParameter: Missing required parameter in request: TransitGatewayRouteTableId.

**Comment by rocki9satya** [comment] 2022-06-05 03:37
I see the below are disabled in the spokes:
# transit_gateway_default_route_table_association = false
  # transit_gateway_default_route_table_propagation = false

Once i enable the error goes away , what i understand to use with RAM for tgw we need to be enabled for the following flag :
 transit_gateway_default_route_table_association
  transit_gateway_default_route_table_propagation

Is it bug or there is some design consideration to make the above flag false?

**Comment by aandsco** [comment] 2022-06-05 17:43
Default route table association and propagation are disabled by design, this is to stop unwanted behaviour and should be followed. Enabling these breaks the solution.

The previous PR dealt with some standardisation of case and descriptions. This could potentially cause issues if the example wasn’t also updated correct. 

What params are you using for the spike VPC? 

Looks like an issue with the data source looking up the TGW route table Ids.

**Comment by aandsco** [comment] 2022-06-05 17:44
The data lookup has failed to get the route table ID form reading the error message. 

I suspect this is to do the TGW route table name or relating to the env?

**Comment by aandsco** [comment] 2022-06-06 09:37
I have just done a full clean deploy of a network hub and spoke account. Both deployed successfully with zero issues.

This issue is due to mis configuration or changes you have made to the solution.

Closing issue due to user error or misconfiguration.

**Closed as completed by aandsco** 2022-06-06 09:37 UTC
